name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_and_test:
    name: "Lint & Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: echo npm version "$(npm --version)"
      - run: npm install --ignore-scripts && lerna link && lerna bootstrap
      - run: npm run lint
      - run: npm run type-check
      - run: npm run test
